server:
  port: 8085

jwt.secret: 'local'

# Database configuration flags
DATABASE_TYPE: 'h2'
OBJECT_STORAGE_TYPE: db #db or s3-minio or smb

# Common datasource configuration
spring:
  jpa:
    hibernate:
      ddl-auto: update
      # ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        webAllowOthers: true
        autostart: true
  boot:
    admin:
      client:
        url: url
        enable: false
        auto-registration: true
        instance:
          name: Docker-util

# actuator
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"

# -----------------------------------H2 specific configuration-----------------------------------

H2_DB: '/config/Coding/docker-util-workspace/db/h2'
H2_USERNAME: 'sa'
H2_PASSWORD: 'password'

# -----------------------------------MySQL specific configuration-----------------------------------

# MYSQL_HOST: '10.24.24.2'
# MYSQL_PORT: 3306
# MYSQL_DB: 'Docker_util'
# MYSQL_USERNAME: 'docker_util'
# MYSQL_PASSWORD: 'docker_util'
# MYSQL_USE_SSL: 'false'

# -----------------------------------Redis specific configuration-----------------------------------
REDIS_ENABLED: false
# REDIS_HOST: "10.24.24.2"
# REDIS_PORT: 6379
# REDIS_USERNAME: 
# REDIS_PASSWORD: 

# -----------------------------------Object Storage specific configuration-----------------------------------
# SMB_HOST: 10.24.24.2
# SMB_PORT: 445
# SMB_DOMAIN: cyberpower
# SMB_USERNAME: smb_file_manager
# SMB_PASSWORD: smb_file_manager
# SMB_SHARE_AND_DIR: Business/Smb_file_manager_test

# S3_URL: https://minio-api.viescloud.com
# S3_USERNAME: hagyKiJbLn85U1qnLsgN
# S3_PASSWORD: XP4WvxNs8Ant9I4BZrY0b2exA6MrU2rZTin3PawM
# S3_BUCKET: viescloud-test